110 LET X=10
140 PRINT "String operations:"
150 LET A$ = "HELLO"
160 LET B$ = "WORLD"
170 PRINT A$ + " " + B$
180 PRINT "THE LINE ABOVE SHOULD BE HELLO WORLD"
640 PRINT "Combined string and numeric operations:"
650 PRINT A$ + STR$(X) + B$
660 PRINT "THE LINE ABOVE SHOULD BE HELLO 10WORLD"
670 PRINT "Function with string literal: " + CHR$(65) + " is A"
680 PRINT "THE LINE ABOVE SHOULD BE Function with string literal: A is A"
690 PRINT "Nested functions with string: " + CHR$(INT(RND * 26) + 65) + " random"
700 PRINT "THE LINE ABOVE SHOULD SHOW A RANDOM UPPERCASE LETTER BETWEEN Function with string: and random"
800 PRINT
810 PRINT "=== INPUT SPACE TEST ==="
820 PRINT "TYPE: GO EAST (with a space)"
830 INPUT "TEST> ";T$
840 PRINT "YOU TYPED: [";T$;"]"
850 PRINT "LENGTH: ";LEN(T$)
860 P=INSTR(T$," ")
870 PRINT "SPACE AT POSITION: ";P
880 IF P>0 THEN PRINT "WORD 1: [";LEFT$(T$,P-1);"]"
890 IF P>0 THEN PRINT "WORD 2: [";MID$(T$,P+1);"]"
900 IF P=0 THEN PRINT "*** NO SPACE FOUND - BUG! ***"
910 IF P>0 THEN PRINT "*** SPACE PRESERVED - OK! ***"
920 PRINT
930 PRINT "TYPE: GET AXE (with a space)"
940 INPUT "TEST> ";U$
950 PRINT "YOU TYPED: [";U$;"]"
960 PRINT "LENGTH: ";LEN(U$)
970 Q=INSTR(U$," ")
980 PRINT "SPACE AT POSITION: ";Q
990 IF Q>0 THEN PRINT "WORD 1: [";LEFT$(U$,Q-1);"]"
995 IF Q>0 THEN PRINT "WORD 2: [";MID$(U$,Q+1);"]"
996 IF Q=0 THEN PRINT "*** NO SPACE FOUND - BUG! ***"
997 IF Q>0 THEN PRINT "*** SPACE PRESERVED - OK! ***"
998 PRINT "END OF TESTS"
